// Code generated by protoc-gen-go. DO NOT EDIT.
// source: torreServer.proto

package torreServer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_f278bdd86b34fa07, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

type Runway struct {
	Runway               int32    `protobuf:"varint,1,opt,name=runway,proto3" json:"runway,omitempty"`
	AirportName          string   `protobuf:"bytes,2,opt,name=airportName,proto3" json:"airportName,omitempty"`
	PreCode              string   `protobuf:"bytes,3,opt,name=preCode,proto3" json:"preCode,omitempty"`
	Height               int32    `protobuf:"varint,4,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Runway) Reset()         { *m = Runway{} }
func (m *Runway) String() string { return proto.CompactTextString(m) }
func (*Runway) ProtoMessage()    {}
func (*Runway) Descriptor() ([]byte, []int) {
	return fileDescriptor_f278bdd86b34fa07, []int{1}
}

func (m *Runway) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Runway.Unmarshal(m, b)
}
func (m *Runway) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Runway.Marshal(b, m, deterministic)
}
func (m *Runway) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Runway.Merge(m, src)
}
func (m *Runway) XXX_Size() int {
	return xxx_messageInfo_Runway.Size(m)
}
func (m *Runway) XXX_DiscardUnknown() {
	xxx_messageInfo_Runway.DiscardUnknown(m)
}

var xxx_messageInfo_Runway proto.InternalMessageInfo

func (m *Runway) GetRunway() int32 {
	if m != nil {
		return m.Runway
	}
	return 0
}

func (m *Runway) GetAirportName() string {
	if m != nil {
		return m.AirportName
	}
	return ""
}

func (m *Runway) GetPreCode() string {
	if m != nil {
		return m.PreCode
	}
	return ""
}

func (m *Runway) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type ArrivingPlane struct {
	SrcAirport           string   `protobuf:"bytes,1,opt,name=srcAirport,proto3" json:"srcAirport,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,4,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ArrivingPlane) Reset()         { *m = ArrivingPlane{} }
func (m *ArrivingPlane) String() string { return proto.CompactTextString(m) }
func (*ArrivingPlane) ProtoMessage()    {}
func (*ArrivingPlane) Descriptor() ([]byte, []int) {
	return fileDescriptor_f278bdd86b34fa07, []int{2}
}

func (m *ArrivingPlane) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ArrivingPlane.Unmarshal(m, b)
}
func (m *ArrivingPlane) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ArrivingPlane.Marshal(b, m, deterministic)
}
func (m *ArrivingPlane) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ArrivingPlane.Merge(m, src)
}
func (m *ArrivingPlane) XXX_Size() int {
	return xxx_messageInfo_ArrivingPlane.Size(m)
}
func (m *ArrivingPlane) XXX_DiscardUnknown() {
	xxx_messageInfo_ArrivingPlane.DiscardUnknown(m)
}

var xxx_messageInfo_ArrivingPlane proto.InternalMessageInfo

func (m *ArrivingPlane) GetSrcAirport() string {
	if m != nil {
		return m.SrcAirport
	}
	return ""
}

func (m *ArrivingPlane) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *ArrivingPlane) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *ArrivingPlane) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

type DepartingPlane struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Runway               int32    `protobuf:"varint,2,opt,name=runway,proto3" json:"runway,omitempty"`
	Height               int32    `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	AirportName          string   `protobuf:"bytes,4,opt,name=airportName,proto3" json:"airportName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DepartingPlane) Reset()         { *m = DepartingPlane{} }
func (m *DepartingPlane) String() string { return proto.CompactTextString(m) }
func (*DepartingPlane) ProtoMessage()    {}
func (*DepartingPlane) Descriptor() ([]byte, []int) {
	return fileDescriptor_f278bdd86b34fa07, []int{3}
}

func (m *DepartingPlane) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DepartingPlane.Unmarshal(m, b)
}
func (m *DepartingPlane) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DepartingPlane.Marshal(b, m, deterministic)
}
func (m *DepartingPlane) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DepartingPlane.Merge(m, src)
}
func (m *DepartingPlane) XXX_Size() int {
	return xxx_messageInfo_DepartingPlane.Size(m)
}
func (m *DepartingPlane) XXX_DiscardUnknown() {
	xxx_messageInfo_DepartingPlane.DiscardUnknown(m)
}

var xxx_messageInfo_DepartingPlane proto.InternalMessageInfo

func (m *DepartingPlane) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *DepartingPlane) GetRunway() int32 {
	if m != nil {
		return m.Runway
	}
	return 0
}

func (m *DepartingPlane) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *DepartingPlane) GetAirportName() string {
	if m != nil {
		return m.AirportName
	}
	return ""
}

type PlaneData struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	CurrFuel             int32    `protobuf:"varint,2,opt,name=currFuel,proto3" json:"currFuel,omitempty"`
	MaxFuel              int32    `protobuf:"varint,3,opt,name=maxFuel,proto3" json:"maxFuel,omitempty"`
	CurrWeight           int32    `protobuf:"varint,4,opt,name=currWeight,proto3" json:"currWeight,omitempty"`
	MaxWeight            int32    `protobuf:"varint,5,opt,name=maxWeight,proto3" json:"maxWeight,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaneData) Reset()         { *m = PlaneData{} }
func (m *PlaneData) String() string { return proto.CompactTextString(m) }
func (*PlaneData) ProtoMessage()    {}
func (*PlaneData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f278bdd86b34fa07, []int{4}
}

func (m *PlaneData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaneData.Unmarshal(m, b)
}
func (m *PlaneData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaneData.Marshal(b, m, deterministic)
}
func (m *PlaneData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaneData.Merge(m, src)
}
func (m *PlaneData) XXX_Size() int {
	return xxx_messageInfo_PlaneData.Size(m)
}
func (m *PlaneData) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaneData.DiscardUnknown(m)
}

var xxx_messageInfo_PlaneData proto.InternalMessageInfo

func (m *PlaneData) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *PlaneData) GetCurrFuel() int32 {
	if m != nil {
		return m.CurrFuel
	}
	return 0
}

func (m *PlaneData) GetMaxFuel() int32 {
	if m != nil {
		return m.MaxFuel
	}
	return 0
}

func (m *PlaneData) GetCurrWeight() int32 {
	if m != nil {
		return m.CurrWeight
	}
	return 0
}

func (m *PlaneData) GetMaxWeight() int32 {
	if m != nil {
		return m.MaxWeight
	}
	return 0
}

type TakeoffStatus struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=errorCode,proto3" json:"errorCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TakeoffStatus) Reset()         { *m = TakeoffStatus{} }
func (m *TakeoffStatus) String() string { return proto.CompactTextString(m) }
func (*TakeoffStatus) ProtoMessage()    {}
func (*TakeoffStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_f278bdd86b34fa07, []int{5}
}

func (m *TakeoffStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TakeoffStatus.Unmarshal(m, b)
}
func (m *TakeoffStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TakeoffStatus.Marshal(b, m, deterministic)
}
func (m *TakeoffStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TakeoffStatus.Merge(m, src)
}
func (m *TakeoffStatus) XXX_Size() int {
	return xxx_messageInfo_TakeoffStatus.Size(m)
}
func (m *TakeoffStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_TakeoffStatus.DiscardUnknown(m)
}

var xxx_messageInfo_TakeoffStatus proto.InternalMessageInfo

func (m *TakeoffStatus) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

type Flight struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Time                 string   `protobuf:"bytes,2,opt,name=time,proto3" json:"time,omitempty"`
	Airport              string   `protobuf:"bytes,3,opt,name=airport,proto3" json:"airport,omitempty"`
	Type                 bool     `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Flight) Reset()         { *m = Flight{} }
func (m *Flight) String() string { return proto.CompactTextString(m) }
func (*Flight) ProtoMessage()    {}
func (*Flight) Descriptor() ([]byte, []int) {
	return fileDescriptor_f278bdd86b34fa07, []int{6}
}

func (m *Flight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Flight.Unmarshal(m, b)
}
func (m *Flight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Flight.Marshal(b, m, deterministic)
}
func (m *Flight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Flight.Merge(m, src)
}
func (m *Flight) XXX_Size() int {
	return xxx_messageInfo_Flight.Size(m)
}
func (m *Flight) XXX_DiscardUnknown() {
	xxx_messageInfo_Flight.DiscardUnknown(m)
}

var xxx_messageInfo_Flight proto.InternalMessageInfo

func (m *Flight) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Flight) GetTime() string {
	if m != nil {
		return m.Time
	}
	return ""
}

func (m *Flight) GetAirport() string {
	if m != nil {
		return m.Airport
	}
	return ""
}

func (m *Flight) GetType() bool {
	if m != nil {
		return m.Type
	}
	return false
}

type PlaneHeight struct {
	Height               int32    `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaneHeight) Reset()         { *m = PlaneHeight{} }
func (m *PlaneHeight) String() string { return proto.CompactTextString(m) }
func (*PlaneHeight) ProtoMessage()    {}
func (*PlaneHeight) Descriptor() ([]byte, []int) {
	return fileDescriptor_f278bdd86b34fa07, []int{7}
}

func (m *PlaneHeight) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaneHeight.Unmarshal(m, b)
}
func (m *PlaneHeight) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaneHeight.Marshal(b, m, deterministic)
}
func (m *PlaneHeight) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaneHeight.Merge(m, src)
}
func (m *PlaneHeight) XXX_Size() int {
	return xxx_messageInfo_PlaneHeight.Size(m)
}
func (m *PlaneHeight) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaneHeight.DiscardUnknown(m)
}

var xxx_messageInfo_PlaneHeight proto.InternalMessageInfo

func (m *PlaneHeight) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type AirportInfo struct {
	Ip                   string   `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
	Port                 int32    `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AirportInfo) Reset()         { *m = AirportInfo{} }
func (m *AirportInfo) String() string { return proto.CompactTextString(m) }
func (*AirportInfo) ProtoMessage()    {}
func (*AirportInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_f278bdd86b34fa07, []int{8}
}

func (m *AirportInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AirportInfo.Unmarshal(m, b)
}
func (m *AirportInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AirportInfo.Marshal(b, m, deterministic)
}
func (m *AirportInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AirportInfo.Merge(m, src)
}
func (m *AirportInfo) XXX_Size() int {
	return xxx_messageInfo_AirportInfo.Size(m)
}
func (m *AirportInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_AirportInfo.DiscardUnknown(m)
}

var xxx_messageInfo_AirportInfo proto.InternalMessageInfo

func (m *AirportInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *AirportInfo) GetPort() int32 {
	if m != nil {
		return m.Port
	}
	return 0
}

func init() {
	proto.RegisterType((*Empty)(nil), "Empty")
	proto.RegisterType((*Runway)(nil), "Runway")
	proto.RegisterType((*ArrivingPlane)(nil), "ArrivingPlane")
	proto.RegisterType((*DepartingPlane)(nil), "DepartingPlane")
	proto.RegisterType((*PlaneData)(nil), "PlaneData")
	proto.RegisterType((*TakeoffStatus)(nil), "TakeoffStatus")
	proto.RegisterType((*Flight)(nil), "Flight")
	proto.RegisterType((*PlaneHeight)(nil), "planeHeight")
	proto.RegisterType((*AirportInfo)(nil), "AirportInfo")
}

func init() { proto.RegisterFile("torreServer.proto", fileDescriptor_f278bdd86b34fa07) }

var fileDescriptor_f278bdd86b34fa07 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x54, 0xdd, 0x6a, 0xdb, 0x4c,
	0x10, 0x45, 0x8e, 0x7f, 0xa2, 0xb1, 0xad, 0xf0, 0xed, 0xc5, 0x87, 0x30, 0xa5, 0x35, 0x82, 0x16,
	0xb7, 0x90, 0x85, 0xba, 0x4f, 0x10, 0x92, 0x86, 0x14, 0x4a, 0x29, 0x4a, 0x21, 0x77, 0x85, 0xad,
	0x3c, 0xb6, 0x97, 0xd8, 0x5a, 0x75, 0xb4, 0x72, 0xe2, 0xe7, 0xe8, 0xcb, 0xf4, 0xf1, 0xca, 0xee,
	0xea, 0xb7, 0x49, 0xef, 0x66, 0x66, 0x8f, 0xcf, 0x99, 0x39, 0x33, 0x32, 0xfc, 0xa7, 0x15, 0x11,
	0xde, 0x22, 0x1d, 0x90, 0x78, 0x46, 0x4a, 0xab, 0x68, 0x04, 0x83, 0x8f, 0xfb, 0x4c, 0x1f, 0x23,
	0x0d, 0xc3, 0xb8, 0x48, 0x1f, 0xc4, 0x91, 0xfd, 0x0f, 0x43, 0xb2, 0x51, 0xe8, 0xcd, 0xbd, 0xc5,
	0x20, 0x2e, 0x33, 0x36, 0x87, 0xb1, 0x90, 0x94, 0x29, 0xd2, 0x5f, 0xc4, 0x1e, 0xc3, 0xde, 0xdc,
	0x5b, 0xf8, 0x71, 0xbb, 0xc4, 0x42, 0x18, 0x65, 0x84, 0x97, 0x6a, 0x85, 0xe1, 0x89, 0x7d, 0xad,
	0x52, 0xc3, 0xb9, 0x45, 0xb9, 0xd9, 0xea, 0xb0, 0xef, 0x38, 0x5d, 0x16, 0x6d, 0x60, 0x7a, 0x41,
	0x24, 0x0f, 0x32, 0xdd, 0x7c, 0xdd, 0x89, 0x14, 0xd9, 0x4b, 0x80, 0x9c, 0x92, 0x0b, 0x47, 0x6a,
	0x1b, 0xf0, 0xe3, 0x56, 0x85, 0x31, 0xe8, 0x27, 0x86, 0xdf, 0xa9, 0xdb, 0x98, 0x05, 0xd0, 0x93,
	0x59, 0xa9, 0xd8, 0x93, 0x99, 0xc1, 0xd8, 0x5f, 0x3b, 0x29, 0x1b, 0x47, 0x07, 0x08, 0xae, 0x30,
	0x13, 0xa4, 0x6b, 0xa5, 0x8a, 0xc9, 0x6b, 0x31, 0x35, 0xa3, 0xf7, 0x3a, 0xa3, 0x37, 0xed, 0x9f,
	0xb4, 0xdb, 0xff, 0xdb, 0x92, 0xfe, 0x13, 0x4b, 0xa2, 0x5f, 0x1e, 0xf8, 0x56, 0xef, 0x4a, 0x68,
	0xf1, 0xac, 0xe6, 0x0c, 0x4e, 0x93, 0x82, 0xe8, 0xba, 0xc0, 0x5d, 0xa9, 0x5a, 0xe7, 0xc6, 0xd0,
	0xbd, 0x78, 0xb4, 0x4f, 0x4e, 0xb8, 0x4a, 0x8d, 0x4f, 0x06, 0x75, 0xd7, 0x36, 0xb5, 0x55, 0x61,
	0x2f, 0xc0, 0xdf, 0x8b, 0xc7, 0xf2, 0x79, 0x60, 0x9f, 0x9b, 0x42, 0x74, 0x0e, 0xd3, 0x6f, 0xe2,
	0x1e, 0xd5, 0x7a, 0x7d, 0xab, 0x85, 0x2e, 0x72, 0x03, 0x47, 0x22, 0x45, 0x97, 0x55, 0x77, 0x83,
	0xb8, 0x29, 0x44, 0xdf, 0x61, 0x78, 0xbd, 0xb3, 0xb4, 0xcf, 0x0d, 0xc0, 0xa0, 0xaf, 0x65, 0x7d,
	0x10, 0x36, 0x36, 0x8d, 0x97, 0x2e, 0x54, 0x97, 0x20, 0x9a, 0x05, 0xea, 0x63, 0xe6, 0xbc, 0x3a,
	0x8d, 0x6d, 0x1c, 0xbd, 0x86, 0x71, 0x66, 0x3c, 0xba, 0x71, 0xbd, 0x37, 0x6e, 0x7b, 0x9d, 0x63,
	0x79, 0x0f, 0xe3, 0xf2, 0x0c, 0x3e, 0xa5, 0x6b, 0x55, 0xae, 0xdd, 0x7b, 0xb2, 0xf6, 0x5e, 0xb3,
	0xf6, 0xe5, 0x6f, 0x0f, 0x7c, 0xad, 0x1e, 0x90, 0x6e, 0x54, 0xae, 0xd9, 0x5b, 0x08, 0x08, 0x7f,
	0x16, 0x98, 0xeb, 0xcf, 0x22, 0x5d, 0xc9, 0x74, 0xc3, 0x02, 0xde, 0x39, 0xbf, 0xd9, 0x88, 0x97,
	0x1f, 0xc1, 0xbb, 0x1a, 0x5a, 0x1a, 0xc5, 0xce, 0x78, 0xf7, 0x80, 0xda, 0xd8, 0x49, 0xb2, 0xc5,
	0xe4, 0xbe, 0x42, 0x02, 0xaf, 0x37, 0x3e, 0x0b, 0x78, 0xd7, 0xe8, 0x05, 0x8c, 0xf4, 0xbf, 0x08,
	0x27, 0xbc, 0x35, 0xde, 0xf2, 0x0e, 0x7c, 0x67, 0x8a, 0xe9, 0xfc, 0x0d, 0x4c, 0x53, 0xa5, 0xe5,
	0xfa, 0x58, 0x35, 0x5e, 0x89, 0xcf, 0x26, 0xbc, 0x6d, 0x5d, 0x04, 0x67, 0x0e, 0xe7, 0xa8, 0x0b,
	0xc2, 0x06, 0x39, 0xe4, 0xf6, 0x4b, 0x5f, 0x9e, 0x03, 0xe4, 0x09, 0x21, 0xa6, 0x96, 0xf9, 0x15,
	0xc0, 0x4e, 0x3a, 0x43, 0x70, 0xc5, 0x46, 0xdc, 0x2d, 0xba, 0x02, 0x2f, 0xbc, 0x1f, 0x43, 0xfb,
	0x47, 0xf1, 0xe1, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x2e, 0x07, 0x4e, 0x98, 0x3d, 0x04, 0x00,
	0x00,
}
