name: grpc
description: Dart implementation of gRPC.
version: 0.6.6
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/grpc-dart

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  async: '>=1.13.3 <3.0.0'
  googleapis_auth: ^0.2.5+3
  meta: ^1.0.5
  http: '>=0.11.3+17 <0.13.0'
  http2: ^0.1.7

dev_dependencies:
  mockito: ^3.0.0
  test: ^1.3.0
