name: controltower
description: Dart Control Tower.
homepage: https://github.com/nachotp/DS-planesync

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  async: '>=1.13.3 <3.0.0'
  grpc:
    path: ../
  protobuf: ^0.10.1

dev_dependencies:
  test: ^1.3.0
