# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: torreServer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='torreServer.proto',
  package='main',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11torreServer.proto\x12\x04main\"\x07\n\x05\x45mpty\"N\n\x06Runway\x12\x0e\n\x06runway\x18\x01 \x01(\x05\x12\x13\n\x0b\x61irportName\x18\x02 \x01(\t\x12\x0f\n\x07preCode\x18\x03 \x01(\t\x12\x0e\n\x06height\x18\x04 \x01(\x05\"K\n\rArrivingPlane\x12\x12\n\nsrcAirport\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\"S\n\x0e\x44\x65partingPlane\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0e\n\x06runway\x18\x02 \x01(\x05\x12\x0e\n\x06height\x18\x03 \x01(\x05\x12\x13\n\x0b\x61irportName\x18\x04 \x01(\t\"c\n\tPlaneData\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x10\n\x08\x63urrFuel\x18\x02 \x01(\x05\x12\x0f\n\x07maxFuel\x18\x03 \x01(\x05\x12\x12\n\ncurrWeight\x18\x04 \x01(\x05\x12\x11\n\tmaxWeight\x18\x05 \x01(\x05\"\"\n\rTakeoffStatus\x12\x11\n\terrorCode\x18\x01 \x01(\x05\"C\n\x06\x46light\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0c\n\x04time\x18\x02 \x01(\t\x12\x0f\n\x07\x61irport\x18\x03 \x01(\t\x12\x0c\n\x04type\x18\x04 \x01(\x05\"\x1d\n\x0bplaneHeight\x12\x0e\n\x06height\x18\x01 \x01(\x05\"\'\n\x0b\x41irportInfo\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\"&\n\nScreenInfo\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\x05\x32\x90\x02\n\ttowerHost\x12\x33\n\x0erequestLanding\x12\x13.main.ArrivingPlane\x1a\x0c.main.Runway\x12\x34\n\x0erequestTakeoff\x12\x14.main.DepartingPlane\x1a\x0c.main.Runway\x12\x34\n\x0c\x63heckTakeoff\x12\x0f.main.PlaneData\x1a\x13.main.TakeoffStatus\x12\x32\n\x07takeoff\x12\x14.main.DepartingPlane\x1a\x11.main.AirportInfo\x12.\n\rscreenConnect\x12\x10.main.ScreenInfo\x1a\x0b.main.Empty2k\n\tplaneHost\x12\x30\n\rnotifyLanding\x12\x0c.main.Runway\x1a\x11.main.planeHeight\x12,\n\x0fnotifyDeparture\x12\x0c.main.Runway\x1a\x0b.main.Empty2:\n\nscreenHost\x12,\n\x0blistFlights\x12\x0c.main.Flight\x1a\x0b.main.Empty\"\x00(\x01\x62\x06proto3')
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='main.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=34,
)


_RUNWAY = _descriptor.Descriptor(
  name='Runway',
  full_name='main.Runway',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='runway', full_name='main.Runway.runway', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='airportName', full_name='main.Runway.airportName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preCode', full_name='main.Runway.preCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='main.Runway.height', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=114,
)


_ARRIVINGPLANE = _descriptor.Descriptor(
  name='ArrivingPlane',
  full_name='main.ArrivingPlane',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='srcAirport', full_name='main.ArrivingPlane.srcAirport', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='main.ArrivingPlane.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='main.ArrivingPlane.ip', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='main.ArrivingPlane.port', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=191,
)


_DEPARTINGPLANE = _descriptor.Descriptor(
  name='DepartingPlane',
  full_name='main.DepartingPlane',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='main.DepartingPlane.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='runway', full_name='main.DepartingPlane.runway', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='main.DepartingPlane.height', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='airportName', full_name='main.DepartingPlane.airportName', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=276,
)


_PLANEDATA = _descriptor.Descriptor(
  name='PlaneData',
  full_name='main.PlaneData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='main.PlaneData.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currFuel', full_name='main.PlaneData.currFuel', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxFuel', full_name='main.PlaneData.maxFuel', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='currWeight', full_name='main.PlaneData.currWeight', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='maxWeight', full_name='main.PlaneData.maxWeight', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=278,
  serialized_end=377,
)


_TAKEOFFSTATUS = _descriptor.Descriptor(
  name='TakeoffStatus',
  full_name='main.TakeoffStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errorCode', full_name='main.TakeoffStatus.errorCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=379,
  serialized_end=413,
)


_FLIGHT = _descriptor.Descriptor(
  name='Flight',
  full_name='main.Flight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='main.Flight.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='time', full_name='main.Flight.time', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='airport', full_name='main.Flight.airport', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='type', full_name='main.Flight.type', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=415,
  serialized_end=482,
)


_PLANEHEIGHT = _descriptor.Descriptor(
  name='planeHeight',
  full_name='main.planeHeight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height', full_name='main.planeHeight.height', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=484,
  serialized_end=513,
)


_AIRPORTINFO = _descriptor.Descriptor(
  name='AirportInfo',
  full_name='main.AirportInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='main.AirportInfo.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='main.AirportInfo.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=515,
  serialized_end=554,
)


_SCREENINFO = _descriptor.Descriptor(
  name='ScreenInfo',
  full_name='main.ScreenInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='main.ScreenInfo.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='main.ScreenInfo.port', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=556,
  serialized_end=594,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Runway'] = _RUNWAY
DESCRIPTOR.message_types_by_name['ArrivingPlane'] = _ARRIVINGPLANE
DESCRIPTOR.message_types_by_name['DepartingPlane'] = _DEPARTINGPLANE
DESCRIPTOR.message_types_by_name['PlaneData'] = _PLANEDATA
DESCRIPTOR.message_types_by_name['TakeoffStatus'] = _TAKEOFFSTATUS
DESCRIPTOR.message_types_by_name['Flight'] = _FLIGHT
DESCRIPTOR.message_types_by_name['planeHeight'] = _PLANEHEIGHT
DESCRIPTOR.message_types_by_name['AirportInfo'] = _AIRPORTINFO
DESCRIPTOR.message_types_by_name['ScreenInfo'] = _SCREENINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'torreServer_pb2'
  # @@protoc_insertion_point(class_scope:main.Empty)
  ))
_sym_db.RegisterMessage(Empty)

Runway = _reflection.GeneratedProtocolMessageType('Runway', (_message.Message,), dict(
  DESCRIPTOR = _RUNWAY,
  __module__ = 'torreServer_pb2'
  # @@protoc_insertion_point(class_scope:main.Runway)
  ))
_sym_db.RegisterMessage(Runway)

ArrivingPlane = _reflection.GeneratedProtocolMessageType('ArrivingPlane', (_message.Message,), dict(
  DESCRIPTOR = _ARRIVINGPLANE,
  __module__ = 'torreServer_pb2'
  # @@protoc_insertion_point(class_scope:main.ArrivingPlane)
  ))
_sym_db.RegisterMessage(ArrivingPlane)

DepartingPlane = _reflection.GeneratedProtocolMessageType('DepartingPlane', (_message.Message,), dict(
  DESCRIPTOR = _DEPARTINGPLANE,
  __module__ = 'torreServer_pb2'
  # @@protoc_insertion_point(class_scope:main.DepartingPlane)
  ))
_sym_db.RegisterMessage(DepartingPlane)

PlaneData = _reflection.GeneratedProtocolMessageType('PlaneData', (_message.Message,), dict(
  DESCRIPTOR = _PLANEDATA,
  __module__ = 'torreServer_pb2'
  # @@protoc_insertion_point(class_scope:main.PlaneData)
  ))
_sym_db.RegisterMessage(PlaneData)

TakeoffStatus = _reflection.GeneratedProtocolMessageType('TakeoffStatus', (_message.Message,), dict(
  DESCRIPTOR = _TAKEOFFSTATUS,
  __module__ = 'torreServer_pb2'
  # @@protoc_insertion_point(class_scope:main.TakeoffStatus)
  ))
_sym_db.RegisterMessage(TakeoffStatus)

Flight = _reflection.GeneratedProtocolMessageType('Flight', (_message.Message,), dict(
  DESCRIPTOR = _FLIGHT,
  __module__ = 'torreServer_pb2'
  # @@protoc_insertion_point(class_scope:main.Flight)
  ))
_sym_db.RegisterMessage(Flight)

planeHeight = _reflection.GeneratedProtocolMessageType('planeHeight', (_message.Message,), dict(
  DESCRIPTOR = _PLANEHEIGHT,
  __module__ = 'torreServer_pb2'
  # @@protoc_insertion_point(class_scope:main.planeHeight)
  ))
_sym_db.RegisterMessage(planeHeight)

AirportInfo = _reflection.GeneratedProtocolMessageType('AirportInfo', (_message.Message,), dict(
  DESCRIPTOR = _AIRPORTINFO,
  __module__ = 'torreServer_pb2'
  # @@protoc_insertion_point(class_scope:main.AirportInfo)
  ))
_sym_db.RegisterMessage(AirportInfo)

ScreenInfo = _reflection.GeneratedProtocolMessageType('ScreenInfo', (_message.Message,), dict(
  DESCRIPTOR = _SCREENINFO,
  __module__ = 'torreServer_pb2'
  # @@protoc_insertion_point(class_scope:main.ScreenInfo)
  ))
_sym_db.RegisterMessage(ScreenInfo)



_TOWERHOST = _descriptor.ServiceDescriptor(
  name='towerHost',
  full_name='main.towerHost',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=597,
  serialized_end=869,
  methods=[
  _descriptor.MethodDescriptor(
    name='requestLanding',
    full_name='main.towerHost.requestLanding',
    index=0,
    containing_service=None,
    input_type=_ARRIVINGPLANE,
    output_type=_RUNWAY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='requestTakeoff',
    full_name='main.towerHost.requestTakeoff',
    index=1,
    containing_service=None,
    input_type=_DEPARTINGPLANE,
    output_type=_RUNWAY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='checkTakeoff',
    full_name='main.towerHost.checkTakeoff',
    index=2,
    containing_service=None,
    input_type=_PLANEDATA,
    output_type=_TAKEOFFSTATUS,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='takeoff',
    full_name='main.towerHost.takeoff',
    index=3,
    containing_service=None,
    input_type=_DEPARTINGPLANE,
    output_type=_AIRPORTINFO,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='screenConnect',
    full_name='main.towerHost.screenConnect',
    index=4,
    containing_service=None,
    input_type=_SCREENINFO,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TOWERHOST)

DESCRIPTOR.services_by_name['towerHost'] = _TOWERHOST


_PLANEHOST = _descriptor.ServiceDescriptor(
  name='planeHost',
  full_name='main.planeHost',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=871,
  serialized_end=978,
  methods=[
  _descriptor.MethodDescriptor(
    name='notifyLanding',
    full_name='main.planeHost.notifyLanding',
    index=0,
    containing_service=None,
    input_type=_RUNWAY,
    output_type=_PLANEHEIGHT,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='notifyDeparture',
    full_name='main.planeHost.notifyDeparture',
    index=1,
    containing_service=None,
    input_type=_RUNWAY,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLANEHOST)

DESCRIPTOR.services_by_name['planeHost'] = _PLANEHOST


_SCREENHOST = _descriptor.ServiceDescriptor(
  name='screenHost',
  full_name='main.screenHost',
  file=DESCRIPTOR,
  index=2,
  serialized_options=None,
  serialized_start=980,
  serialized_end=1038,
  methods=[
  _descriptor.MethodDescriptor(
    name='listFlights',
    full_name='main.screenHost.listFlights',
    index=0,
    containing_service=None,
    input_type=_FLIGHT,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SCREENHOST)

DESCRIPTOR.services_by_name['screenHost'] = _SCREENHOST

# @@protoc_insertion_point(module_scope)
