# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: torreServer.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='torreServer.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x11torreServer.proto\"\x07\n\x05\x45mpty\">\n\x06Runway\x12\x0e\n\x06runway\x18\x01 \x01(\x05\x12\x13\n\x0b\x61irportName\x18\x02 \x01(\t\x12\x0f\n\x07preCode\x18\x03 \x01(\t\"K\n\rArrivingPlane\x12\x12\n\nsrcAirport\x18\x01 \x01(\t\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\n\n\x02ip\x18\x03 \x01(\t\x12\x0c\n\x04port\x18\x04 \x01(\x05\".\n\x0e\x44\x65partingPlane\x12\x0c\n\x04\x63ode\x18\x01 \x01(\t\x12\x0e\n\x06runway\x18\x02 \x01(\x05\"i\n\x0e\x43urrentFlights\x1aW\n\x06\x46light\x12)\n\x04type\x18\x01 \x01(\x0e\x32\x1b.CurrentFlights.Flight.Type\"\"\n\x04Type\x12\x0b\n\x07\x41RRIVAL\x10\x00\x12\r\n\tDEPARTURE\x10\x01\x32\xb6\x01\n\ttowerHost\x12)\n\x0erequestLanding\x12\x0e.ArrivingPlane\x1a\x07.Runway\x12*\n\x0erequestTakeoff\x12\x0f.DepartingPlane\x1a\x07.Runway\x12\"\n\x07takeoff\x12\x0f.DepartingPlane\x1a\x06.Empty\x12.\n\nlistLanded\x12\x0e.ArrivingPlane\x1a\x0e.ArrivingPlane0\x01\x32Q\n\tplaneHost\x12 \n\rnotifyLanding\x12\x07.Runway\x1a\x06.Empty\x12\"\n\x0fnotifyDeparture\x12\x07.Runway\x1a\x06.Emptyb\x06proto3')
)



_CURRENTFLIGHTS_FLIGHT_TYPE = _descriptor.EnumDescriptor(
  name='Type',
  full_name='CurrentFlights.Flight.Type',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ARRIVAL', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DEPARTURE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=290,
  serialized_end=324,
)
_sym_db.RegisterEnumDescriptor(_CURRENTFLIGHTS_FLIGHT_TYPE)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=28,
)


_RUNWAY = _descriptor.Descriptor(
  name='Runway',
  full_name='Runway',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='runway', full_name='Runway.runway', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='airportName', full_name='Runway.airportName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='preCode', full_name='Runway.preCode', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=92,
)


_ARRIVINGPLANE = _descriptor.Descriptor(
  name='ArrivingPlane',
  full_name='ArrivingPlane',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='srcAirport', full_name='ArrivingPlane.srcAirport', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='code', full_name='ArrivingPlane.code', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='ip', full_name='ArrivingPlane.ip', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='ArrivingPlane.port', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=169,
)


_DEPARTINGPLANE = _descriptor.Descriptor(
  name='DepartingPlane',
  full_name='DepartingPlane',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='DepartingPlane.code', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='runway', full_name='DepartingPlane.runway', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=171,
  serialized_end=217,
)


_CURRENTFLIGHTS_FLIGHT = _descriptor.Descriptor(
  name='Flight',
  full_name='CurrentFlights.Flight',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='CurrentFlights.Flight.type', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _CURRENTFLIGHTS_FLIGHT_TYPE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=324,
)

_CURRENTFLIGHTS = _descriptor.Descriptor(
  name='CurrentFlights',
  full_name='CurrentFlights',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[_CURRENTFLIGHTS_FLIGHT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=324,
)

_CURRENTFLIGHTS_FLIGHT.fields_by_name['type'].enum_type = _CURRENTFLIGHTS_FLIGHT_TYPE
_CURRENTFLIGHTS_FLIGHT.containing_type = _CURRENTFLIGHTS
_CURRENTFLIGHTS_FLIGHT_TYPE.containing_type = _CURRENTFLIGHTS_FLIGHT
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['Runway'] = _RUNWAY
DESCRIPTOR.message_types_by_name['ArrivingPlane'] = _ARRIVINGPLANE
DESCRIPTOR.message_types_by_name['DepartingPlane'] = _DEPARTINGPLANE
DESCRIPTOR.message_types_by_name['CurrentFlights'] = _CURRENTFLIGHTS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), dict(
  DESCRIPTOR = _EMPTY,
  __module__ = 'torreServer_pb2'
  # @@protoc_insertion_point(class_scope:Empty)
  ))
_sym_db.RegisterMessage(Empty)

Runway = _reflection.GeneratedProtocolMessageType('Runway', (_message.Message,), dict(
  DESCRIPTOR = _RUNWAY,
  __module__ = 'torreServer_pb2'
  # @@protoc_insertion_point(class_scope:Runway)
  ))
_sym_db.RegisterMessage(Runway)

ArrivingPlane = _reflection.GeneratedProtocolMessageType('ArrivingPlane', (_message.Message,), dict(
  DESCRIPTOR = _ARRIVINGPLANE,
  __module__ = 'torreServer_pb2'
  # @@protoc_insertion_point(class_scope:ArrivingPlane)
  ))
_sym_db.RegisterMessage(ArrivingPlane)

DepartingPlane = _reflection.GeneratedProtocolMessageType('DepartingPlane', (_message.Message,), dict(
  DESCRIPTOR = _DEPARTINGPLANE,
  __module__ = 'torreServer_pb2'
  # @@protoc_insertion_point(class_scope:DepartingPlane)
  ))
_sym_db.RegisterMessage(DepartingPlane)

CurrentFlights = _reflection.GeneratedProtocolMessageType('CurrentFlights', (_message.Message,), dict(

  Flight = _reflection.GeneratedProtocolMessageType('Flight', (_message.Message,), dict(
    DESCRIPTOR = _CURRENTFLIGHTS_FLIGHT,
    __module__ = 'torreServer_pb2'
    # @@protoc_insertion_point(class_scope:CurrentFlights.Flight)
    ))
  ,
  DESCRIPTOR = _CURRENTFLIGHTS,
  __module__ = 'torreServer_pb2'
  # @@protoc_insertion_point(class_scope:CurrentFlights)
  ))
_sym_db.RegisterMessage(CurrentFlights)
_sym_db.RegisterMessage(CurrentFlights.Flight)



_TOWERHOST = _descriptor.ServiceDescriptor(
  name='towerHost',
  full_name='towerHost',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=327,
  serialized_end=509,
  methods=[
  _descriptor.MethodDescriptor(
    name='requestLanding',
    full_name='towerHost.requestLanding',
    index=0,
    containing_service=None,
    input_type=_ARRIVINGPLANE,
    output_type=_RUNWAY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='requestTakeoff',
    full_name='towerHost.requestTakeoff',
    index=1,
    containing_service=None,
    input_type=_DEPARTINGPLANE,
    output_type=_RUNWAY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='takeoff',
    full_name='towerHost.takeoff',
    index=2,
    containing_service=None,
    input_type=_DEPARTINGPLANE,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='listLanded',
    full_name='towerHost.listLanded',
    index=3,
    containing_service=None,
    input_type=_ARRIVINGPLANE,
    output_type=_ARRIVINGPLANE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_TOWERHOST)

DESCRIPTOR.services_by_name['towerHost'] = _TOWERHOST


_PLANEHOST = _descriptor.ServiceDescriptor(
  name='planeHost',
  full_name='planeHost',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=511,
  serialized_end=592,
  methods=[
  _descriptor.MethodDescriptor(
    name='notifyLanding',
    full_name='planeHost.notifyLanding',
    index=0,
    containing_service=None,
    input_type=_RUNWAY,
    output_type=_EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='notifyDeparture',
    full_name='planeHost.notifyDeparture',
    index=1,
    containing_service=None,
    input_type=_RUNWAY,
    output_type=_EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PLANEHOST)

DESCRIPTOR.services_by_name['planeHost'] = _PLANEHOST

# @@protoc_insertion_point(module_scope)
